name: base
channels:
  - conda-forge
  - anaconda
  - oxfordcontrol
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.0=py37_0
  - asn1crypto=0.24.0=py37_0
  - astor=0.7.1=py_0
  - attrs=19.1.0=py37_1
  - autopep8=1.4.4=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=openblas
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=h516909a_1
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.9.11=py37_0
  - cffi=1.12.2=py37h2e261b9_1
  - chardet=3.0.4=py37_1
  - conda=4.7.12=py37_0
  - conda-package-handling=1.4.1=py37_0
  - cryptography=2.6.1=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.3.2=py_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.1.7=py_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.23.0=py37he9ae1f9_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=nompi_py37h513d04c_100
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.5.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.4=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - libarchive=3.3.3=h5d8350f_5
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.8.0=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.4.1=py37h7ec2d77_0
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h14c3975_1000
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mock=3.0.5=py37_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.1=py37_0
  - numpy=1.16.0=py37h99e49ec_1
  - numpy-base=1.16.0=py37h2f8d375_1
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_1
  - pandas=0.25.1=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h049681c_0
  - parso=0.5.1=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.0.3=py37_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - protobuf=3.8.0=py37he1b5a44_1
  - ptyprocess=0.6.0=py37_0
  - pycodestyle=2.5.0=py37_0
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pydot=1.4.1=py37_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.14.11=py37h7b6447c_0
  - pysocks=1.6.8=py37_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - python-libarchive-c=2.8=py37_1004
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h7b6447c_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.5.5=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - scipy=1.3.1=py37h921218d_2
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.27.2=h7b6447c_0
  - statsmodels=0.10.1=py37hdd07704_0
  - tensorboard=1.13.1=py37hf484d3e_0
  - tensorflow=1.13.1=gpu_py37hc158e3b_0
  - tensorflow-base=1.13.1=gpu_py37h8d69cac_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.35.0=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.15.6=py_0
  - wheel=0.33.1=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - appdirs==1.4.3
    - colorama==0.4.1
    - findiff==0.6.3
    - future==0.17.1
    - google-images-download==2.8.0
    - imageio==2.5.0
    - jupyter-tensorboard==0.1.10
    - keras-vis==0.4.1
    - networkx==2.3
    - python-telegram-bot==11.1.0
    - pywavelets==1.0.3
    - scikit-image==0.15.0
    - selenium==3.141.0
    - telegram-send==0.20

